version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: hospital
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build: .
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=hospital
      - JWT_SECRET=your_secret_key
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data:
